use_frameworks!

platform :ios, '10.0'

target 'ANKeyboardHandler_Example' do
  pod 'ANKeyboardHandler', :path => '../'

  target 'ANKeyboardHandler_Tests' do
    inherit! :search_paths

    
  end
end
